// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inquiries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInquiry = `-- name: CreateInquiry :one
INSERT INTO inquiries (listing_id, renter_id, message) VALUES ($1, $2, $3) RETURNING id, listing_id, renter_id, message, status, created_at, updated_at
`

type CreateInquiryParams struct {
	ListingID pgtype.UUID `json:"listing_id"`
	RenterID  pgtype.UUID `json:"renter_id"`
	Message   string      `json:"message"`
}

func (q *Queries) CreateInquiry(ctx context.Context, arg CreateInquiryParams) (Inquiry, error) {
	row := q.db.QueryRow(ctx, createInquiry, arg.ListingID, arg.RenterID, arg.Message)
	var i Inquiry
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.RenterID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inquiriesByRenter = `-- name: InquiriesByRenter :many
SELECT id, listing_id, renter_id, message, status, created_at, updated_at FROM inquiries WHERE renter_id = $1 ORDER BY created_at DESC
`

func (q *Queries) InquiriesByRenter(ctx context.Context, renterID pgtype.UUID) ([]Inquiry, error) {
	rows, err := q.db.Query(ctx, inquiriesByRenter, renterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inquiry{}
	for rows.Next() {
		var i Inquiry
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.RenterID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
