// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const publishListing = `-- name: PublishListing :execrows
UPDATE listings SET status = 'published', published_at = COALESCE(published_at, now()), updated_at = now()
WHERE id = $1 AND status IN ('draft', 'unpublished')
`

func (q *Queries) PublishListing(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, publishListing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publishedListingBySlug = `-- name: PublishedListingBySlug :one
SELECT id, property_id, unit_id, slug, title, description, rent_amount, deposit_amount, amenities, status, published_at, created_at, updated_at FROM listings WHERE slug = $1 AND status = 'published'
`

func (q *Queries) PublishedListingBySlug(ctx context.Context, slug string) (Listing, error) {
	row := q.db.QueryRow(ctx, publishedListingBySlug, slug)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.UnitID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.RentAmount,
		&i.DepositAmount,
		&i.Amenities,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
