// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	Metadata       []byte             `json:"metadata"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      string             `json:"user_agent"`
	RequestID      string             `json:"request_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Inquiry struct {
	ID        pgtype.UUID        `json:"id"`
	ListingID pgtype.UUID        `json:"listing_id"`
	RenterID  pgtype.UUID        `json:"renter_id"`
	Message   string             `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Listing struct {
	ID            pgtype.UUID        `json:"id"`
	PropertyID    pgtype.UUID        `json:"property_id"`
	UnitID        pgtype.UUID        `json:"unit_id"`
	Slug          string             `json:"slug"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	RentAmount    pgtype.Numeric     `json:"rent_amount"`
	DepositAmount pgtype.Numeric     `json:"deposit_amount"`
	Amenities     []string           `json:"amenities"`
	Status        string             `json:"status"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ListingImage struct {
	ID        pgtype.UUID        `json:"id"`
	ListingID pgtype.UUID        `json:"listing_id"`
	ImageUrl  string             `json:"image_url"`
	AltText   string             `json:"alt_text"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceRequest struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	PropertyID     pgtype.UUID        `json:"property_id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	TenancyID      pgtype.UUID        `json:"tenancy_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID         pgtype.UUID        `json:"id"`
	TenancyID  pgtype.UUID        `json:"tenancy_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Method     string             `json:"method"`
	Reference  string             `json:"reference"`
	Status     string             `json:"status"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	RecordedBy pgtype.UUID        `json:"recorded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Property struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	AddressLine    string             `json:"address_line"`
	Locality       string             `json:"locality"`
	County         string             `json:"county"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Tenancy struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	PropertyID     pgtype.UUID        `json:"property_id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	MonthlyRent    pgtype.Numeric     `json:"monthly_rent"`
	DepositAmount  pgtype.Numeric     `json:"deposit_amount"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Unit struct {
	ID                 pgtype.UUID        `json:"id"`
	PropertyID         pgtype.UUID        `json:"property_id"`
	UnitLabel          string             `json:"unit_label"`
	Bedrooms           int32              `json:"bedrooms"`
	Bathrooms          pgtype.Numeric     `json:"bathrooms"`
	RentAmount         pgtype.Numeric     `json:"rent_amount"`
	DepositAmount      pgtype.Numeric     `json:"deposit_amount"`
	AvailabilityStatus string             `json:"availability_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Phone        string             `json:"phone"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
