// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (tenancy_id, amount, method, reference, status, paid_at, recorded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, tenancy_id, amount, method, reference, status, paid_at, recorded_by, created_at, updated_at
`

type CreatePaymentParams struct {
	TenancyID  pgtype.UUID        `json:"tenancy_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Method     string             `json:"method"`
	Reference  string             `json:"reference"`
	Status     string             `json:"status"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	RecordedBy pgtype.UUID        `json:"recorded_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TenancyID,
		arg.Amount,
		arg.Method,
		arg.Reference,
		arg.Status,
		arg.PaidAt,
		arg.RecordedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenancyID,
		&i.Amount,
		&i.Method,
		&i.Reference,
		&i.Status,
		&i.PaidAt,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsByTenancy = `-- name: PaymentsByTenancy :many
SELECT id, tenancy_id, amount, method, reference, status, paid_at, recorded_by, created_at, updated_at FROM payments WHERE tenancy_id = $1 ORDER BY paid_at DESC
`

func (q *Queries) PaymentsByTenancy(ctx context.Context, tenancyID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, paymentsByTenancy, tenancyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenancyID,
			&i.Amount,
			&i.Method,
			&i.Reference,
			&i.Status,
			&i.PaidAt,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
