// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveTenanciesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Tenancy, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateInquiry(ctx context.Context, arg CreateInquiryParams) (Inquiry, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	InquiriesByRenter(ctx context.Context, renterID pgtype.UUID) ([]Inquiry, error)
	LandlordUnitCounts(ctx context.Context, organizationID pgtype.UUID) (LandlordUnitCountsRow, error)
	MaintenanceByCreator(ctx context.Context, createdBy pgtype.UUID) ([]MaintenanceRequest, error)
	MaintenanceByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]MaintenanceRequest, error)
	PaymentsByTenancy(ctx context.Context, tenancyID pgtype.UUID) ([]Payment, error)
	PropertiesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]PropertiesByOrganizationRow, error)
	PublishListing(ctx context.Context, id pgtype.UUID) (int64, error)
	PublishedListingBySlug(ctx context.Context, slug string) (Listing, error)
	RevokeSession(ctx context.Context, tokenHash []byte) error
	TenanciesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Tenancy, error)
	UnitsByProperty(ctx context.Context, propertyID pgtype.UUID) ([]Unit, error)
	UserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
