// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (actor_user_id, organization_id, action, resource_type, resource_id, metadata, ip_address, user_agent, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAuditLogParams struct {
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     pgtype.UUID `json:"resource_id"`
	Metadata       []byte      `json:"metadata"`
	IpAddress      *netip.Addr `json:"ip_address"`
	UserAgent      string      `json:"user_agent"`
	RequestID      string      `json:"request_id"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorUserID,
		arg.OrganizationID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}
