// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const landlordUnitCounts = `-- name: LandlordUnitCounts :one
SELECT count(*)::int AS total_units,
       count(*) FILTER (WHERE u.availability_status = 'available')::int AS available_units,
       count(*) FILTER (WHERE u.availability_status = 'occupied')::int AS occupied_units
FROM units u JOIN properties p ON p.id = u.property_id WHERE p.organization_id = $1
`

type LandlordUnitCountsRow struct {
	TotalUnits     int32 `json:"total_units"`
	AvailableUnits int32 `json:"available_units"`
	OccupiedUnits  int32 `json:"occupied_units"`
}

func (q *Queries) LandlordUnitCounts(ctx context.Context, organizationID pgtype.UUID) (LandlordUnitCountsRow, error) {
	row := q.db.QueryRow(ctx, landlordUnitCounts, organizationID)
	var i LandlordUnitCountsRow
	err := row.Scan(&i.TotalUnits, &i.AvailableUnits, &i.OccupiedUnits)
	return i, err
}
