// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const maintenanceByCreator = `-- name: MaintenanceByCreator :many
SELECT id, organization_id, property_id, unit_id, tenancy_id, created_by, title, description, priority, status, created_at, updated_at FROM maintenance_requests WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) MaintenanceByCreator(ctx context.Context, createdBy pgtype.UUID) ([]MaintenanceRequest, error) {
	rows, err := q.db.Query(ctx, maintenanceByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceRequest{}
	for rows.Next() {
		var i MaintenanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PropertyID,
			&i.UnitID,
			&i.TenancyID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenanceByOrganization = `-- name: MaintenanceByOrganization :many
SELECT id, organization_id, property_id, unit_id, tenancy_id, created_by, title, description, priority, status, created_at, updated_at FROM maintenance_requests WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) MaintenanceByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]MaintenanceRequest, error) {
	rows, err := q.db.Query(ctx, maintenanceByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceRequest{}
	for rows.Next() {
		var i MaintenanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PropertyID,
			&i.UnitID,
			&i.TenancyID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
