// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: properties.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (organization_id, name, description, address_line, locality, county, status)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, organization_id, name, description, address_line, locality, county, latitude, longitude, status, created_at, updated_at
`

type CreatePropertyParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	AddressLine    string      `json:"address_line"`
	Locality       string      `json:"locality"`
	County         string      `json:"county"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.AddressLine,
		arg.Locality,
		arg.County,
		arg.Status,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.AddressLine,
		&i.Locality,
		&i.County,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const propertiesByOrganization = `-- name: PropertiesByOrganization :many
SELECT id, organization_id, name, description, address_line, locality, county, status, created_at, updated_at
FROM properties WHERE organization_id = $1 ORDER BY created_at DESC
`

type PropertiesByOrganizationRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	AddressLine    string             `json:"address_line"`
	Locality       string             `json:"locality"`
	County         string             `json:"county"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PropertiesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]PropertiesByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, propertiesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PropertiesByOrganizationRow{}
	for rows.Next() {
		var i PropertiesByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.AddressLine,
			&i.Locality,
			&i.County,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
