// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenancies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeTenanciesByTenant = `-- name: ActiveTenanciesByTenant :many
SELECT id, organization_id, property_id, unit_id, tenant_id, start_date, end_date, monthly_rent, deposit_amount, status, created_at, updated_at FROM tenancies WHERE tenant_id = $1 AND status = 'active' ORDER BY start_date DESC
`

func (q *Queries) ActiveTenanciesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Tenancy, error) {
	rows, err := q.db.Query(ctx, activeTenanciesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenancy{}
	for rows.Next() {
		var i Tenancy
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PropertyID,
			&i.UnitID,
			&i.TenantID,
			&i.StartDate,
			&i.EndDate,
			&i.MonthlyRent,
			&i.DepositAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenanciesByOrganization = `-- name: TenanciesByOrganization :many
SELECT id, organization_id, property_id, unit_id, tenant_id, start_date, end_date, monthly_rent, deposit_amount, status, created_at, updated_at FROM tenancies WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) TenanciesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Tenancy, error) {
	rows, err := q.db.Query(ctx, tenanciesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenancy{}
	for rows.Next() {
		var i Tenancy
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PropertyID,
			&i.UnitID,
			&i.TenantID,
			&i.StartDate,
			&i.EndDate,
			&i.MonthlyRent,
			&i.DepositAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
