// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (property_id, unit_label, bedrooms, bathrooms, rent_amount, deposit_amount, availability_status)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, property_id, unit_label, bedrooms, bathrooms, rent_amount, deposit_amount, availability_status, created_at, updated_at
`

type CreateUnitParams struct {
	PropertyID         pgtype.UUID    `json:"property_id"`
	UnitLabel          string         `json:"unit_label"`
	Bedrooms           int32          `json:"bedrooms"`
	Bathrooms          pgtype.Numeric `json:"bathrooms"`
	RentAmount         pgtype.Numeric `json:"rent_amount"`
	DepositAmount      pgtype.Numeric `json:"deposit_amount"`
	AvailabilityStatus string         `json:"availability_status"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.PropertyID,
		arg.UnitLabel,
		arg.Bedrooms,
		arg.Bathrooms,
		arg.RentAmount,
		arg.DepositAmount,
		arg.AvailabilityStatus,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.UnitLabel,
		&i.Bedrooms,
		&i.Bathrooms,
		&i.RentAmount,
		&i.DepositAmount,
		&i.AvailabilityStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unitsByProperty = `-- name: UnitsByProperty :many
SELECT id, property_id, unit_label, bedrooms, bathrooms, rent_amount, deposit_amount, availability_status, created_at, updated_at FROM units WHERE property_id = $1 ORDER BY unit_label
`

func (q *Queries) UnitsByProperty(ctx context.Context, propertyID pgtype.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, unitsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.UnitLabel,
			&i.Bedrooms,
			&i.Bathrooms,
			&i.RentAmount,
			&i.DepositAmount,
			&i.AvailabilityStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
